Assignments/boolean birds
bhs-intro-to-programming/REDshrimpp pull request #2
Opened 2022-09-12 22:11 UTC by REDshrimpp

I finished Boolean birds on friday last week, sorry I forgot to make a pull request for it before

2022-09-13 00:28 UTC, gigamonkey requested changes
Why don't you change the argument name in the last four functions to something suitably generic and then I'll approve this.

2022-09-13 00:28 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isRed = (redBird) => {
This is basically fine. However since the point of this function is to tell whether any bird *is* red, I'd expect the variable name to be more generic. Like `bird` or `name` or maybe `species`. It doesn't matter to the computer but humans understand code better when the names make sense.

2022-09-13 00:30 UTC, gigamonkey reviewed
You can fix all of these in a hurry by right clicking in the editor pane to get a context menu that will have an item "Format document". Select that and it will fix all these spacing issues and make your code prettier.

2022-09-13 00:30 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isFlobbyBird = (isRed,isSpotted) => isRed&&isSpotted
Oh, also you should put spaces around operators and after commas. Like this:

```suggestion
const isFlobbyBird = (isRed, isSpotted) => isRed && isSpotted;
```

2022-09-16 00:22 UTC, gigamonkey requested changes
Sorry it took my so long to notice you had made these changes. You did everything right in terms of tagging me but I missed it anyway. I had one more comment that I'd like you to address and then I'm sure I'll approve it.

2022-09-16 00:22 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isRed = (color) => {
This is still a bit off. The method `isRed` is asking a question about color, yes, but the argument to the function is just the name of a kind of bird. Really all four of the isWhatever methods should probably have the same argument name since they are all accepting the same kind of value: a string which will be the name of the kind of bird. So maybe `name` or `bird` would be good for all four. (Giving them the same argument name is a clue to the human reader that they are all operating on the same kind of value.)

2022-09-16 22:16 UTC, REDshrimpp commented
@gigamonkey just updated let me know what you think

2022-09-20 03:33 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-20 21:40 UTC, merged