Assignments/pig latin
bhs-intro-to-programming/REDshrimpp pull request #3
Opened 2022-09-14 22:05 UTC by REDshrimpp

2022-09-14 23:52 UTC, gigamonkey requested changes
Please clean up the various things I pointed out and get the code into a state where it runs and then I'll approve it.

2022-09-14 23:52 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const pigLatin = (s) => (s.substring(s.search(/[aeiou]/), s.length)+s.substring(0,s.search(/[aeiou]/))+'ay')
You don't need the `()`s around the expression. So this is fine:

```suggestion
const pigLatin = (s) => s.substring(s.search(/[aeiou]/), s.length)+s.substring(0,s.search(/[aeiou]/))+'ay';
```

But this function would also benefit from using a variable like you did in `advancedPigLatin`. Something like

```javascript
const pigLatin = (s) => {
  const i = s.search(/[aeiou]/);
  return s.substring(i) + s.substring(0, i) + 'ay';
};
```

This saves a tiny bit of work for the computer (it only has to search the string once) but more importantly makes everything easier to read because you can understand the first line on its own (ah, we're getting the index of the first vowel) and then read the final expression with that in mind rather than having to understand both things at the same time. Also it's just easier to read and see that the `i` is the same in both places rather than the more complicated `search` expression.

Finally, you should use the one-arg version of `substring` for the first call just because it makes it easier to read at a glance and see that it's going all the way to the end of the string.

2022-09-14 23:52 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  let urmom = s.search(/[aeiou]/)
You should use meaningful variables names. `i` is actually quite a good name for this variable since it a wildly followed convention to name variables that hold index values that. You should get in the habit of writing code to be understood and save your creativity for making interesting programs.

2022-09-14 23:52 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const fakeSpanish = (s) => s + 'o'
I like this playing around with other things!

2022-09-14 23:52 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +fakeSpanish(car)
Sadly, this presumably gives you an error because there's no variable `car`. I think you meant the string `'car'`.

2022-09-15 21:47 UTC, REDshrimpp commented
@gigamonkey I committed the changes that you requested. Review it again and let me know what you think.

2022-09-16 00:23 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-20 21:40 UTC, merged