Projects/personality-quiz
bhs-intro-to-programming/REDshrimpp pull request #35
Opened 2023-01-26 23:31 UTC by REDshrimpp

2023-01-27 23:37 UTC, REDshrimpp commented
hey just commited some changes that aren't working I just want to make sure this gets reviewed.

thank you!

2023-01-28 18:43 UTC, gigamonkey approved these changes
Glad to see you starting to touch the code. It may feel like you didn't get a ton done in terms of total lines of code but getting started is often the biggest hurdle; once you start messing with the code one thing can lead to another and soon you'll be on your way.

2023-01-31 03:27 UTC, gigamonkey approved these changes
Glad we got you to a working state by the end of the day.

2023-02-01 23:36 UTC, gigamonkey requested changes
keep going

2023-02-02 01:50 UTC, gigamonkey approved these changes
I can't quite tell where this is going. Let's chat about it a bit.

2023-02-03 00:48 UTC, gigamonkey approved these changes
Still don't quite get where this is going.

2023-02-05 19:16 UTC, REDshrimpp commented
Hey I just made some more changes over the weekend. There aren't too many and its working right now so you don't have to review it just yet if you don't want to

2023-02-06 23:43 UTC, REDshrimpp commented
Just committed some more changes

(adding an output display & making the questions objects)

2023-02-07 05:09 UTC, gigamonkey approved these changes
Okay, I'm starting to see how this is coming together. It might be a good idea to put in some real questions so it's a bit more concrete. But otherwise, carry on. And you can go ahead and merge this but don't delete the branch and you can make a new PR for your subsequent work.

2023-02-07 05:09 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +const questionRandomizer = () => {
If you use an array of questions you can easily choose questions at random from it:

```
array[Math.floor(Math.random() * array.length)]
```

is a random element of `array`.

2023-02-07 05:09 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +const questions = [question1, question2]
Oh, here's the array. You can get rid of the variables `question1` and `question2` by defining the array with the values direcly:

```javascript
const questions = [
  {charge:'positive', question:'QUESTION 1', influence: 3},
  {charge:'negative', question:'QUESTION 2', influence: 1},
];
```

2023-02-07 05:09 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +const amountOfQuestions = questions.length
And I'd probably just use `questions.length` when you need it rather than defining this variable which is hardly any shorter. (Plus when you're, for instance, looping over `questions` it's nice to see that the loop is going from `i = 0` to `i < questions.length` and be sure that it's a valid loop.

2023-02-07 05:09 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +    return questions[currentQuestion - 1]
If you unconditionally return from a loop, as you do here, it makes the loop superfluous. `x` is never used and the function returns immediately the first iteration of the loop. (The only way the `for` loop could do anything here is if `amountOfQuestions` was not greater than zero in which case the loop would never run and would act as a very odd if statement.

2023-02-07 05:09 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +}
These two functions are almost identical; you should see if you can't factor out the common bits. Especially considering that someday you're probably going to have more than two questions in which case you're going to probably want one function that can deal with any question, not a special function for every question.

Bear in mind—since these functions are used as event handlers—that the event handler is passed an event object that lets you, among other things, determine which exact element the event was generated from.

2023-02-07 23:32 UTC, merged