Projects/personality quiz
bhs-intro-to-programming/REDshrimpp pull request #37
Opened 2023-02-08 23:35 UTC by REDshrimpp

2023-02-09 04:46 UTC, gigamonkey approved these changes
Looks like this is almost there. Hopefully you can write some actual fun questions before Friday.

2023-02-09 04:46 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
>      if (questions[currentQuestion] === 'negative') {
Missing a `.charge` here.

2023-02-10 03:25 UTC, gigamonkey approved these changes
Looking good. Though the "you didn't pass" at the end is kinda harsh. ;-)

2023-02-10 03:25 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +  { charge: 'negative', question: 'do you poor the milk first?', influence: 5 },
"pour"?

2023-02-10 03:25 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +  { charge: 'positive', question: 'cats or dogs', influence: 1 },
uh, this isn't a yes or no question.

2023-02-19 21:36 UTC, gigamonkey approved these changes
Approving this so you can merge it. Your grade will be posted in IC soon.

2023-03-01 02:37 UTC, gigamonkey requested changes
If you want to refactor this, maybe we should have a chat tomorrow about what your goal is.

2023-03-01 23:32 UTC, REDshrimpp commented on projects/personality-quiz/public/scripts/script.js
sometime soon I want to try and figure out how to make the big function take the click input

2023-03-03 01:23 UTC, gigamonkey requested changes
This looks like a good start toward what we were talking about. You should definitely try to get it into some kind of state where you can see, even if only by `console.log`ing that the right functions are being called at the right times. Anyway, keep going!

2023-03-03 01:23 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +  recordYesAnswer(questions[questionNumber])
Oh, it looks like what I was calling `questionNumber` you called `currentQuestion`. That's fine but you need to use the variable name you're actually using.

2023-03-15 01:04 UTC, gigamonkey requested changes
Some issues with when you are selecting a random question. Or possibly I don't understand what you're trying to do here.

2023-03-15 01:04 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +    let selectedQuestion = randomQuestion()
This seems like an odd place to select a random question. Presumably when the user clicks "Yes" they are answering the question displayed on the screen. But you are grabbing a random question and marking it's answer as yes. That seems not right.

2023-03-15 01:04 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +    let selectedQuestion = randomQuestion()
Same comment as above.

2023-03-15 01:04 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +  selectedQuestion.asked = 'yes'
I get why it kind of makes sense to put this here but this function is now doing two thins: selecting a random question (which is what we'd expect from the name) and *also* marking it as asked. I'd rather move the code to mark it as asked to wherever we actually ask the question. (Which at the moment is kinda nowhere since you call this function from the yes and no click handlers which seems wrong to me as discussed below.)

2023-03-17 03:02 UTC, gigamonkey requested changes
I think I found your problem.

2023-03-17 03:02 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +    recordYesAnswer(currentQuestion)
This seems backwards to me. They are clicking yes to answer the currently displayed question and you switch the question and then record the answer for the old question on the new question.

2023-03-19 17:02 UTC, gigamonkey requested changes
Right on. Keep going.

2023-03-19 17:02 UTC, gigamonkey commented on projects/personality-quiz/public/scripts/script.js
> +const no = document.getElementById('noButton');
Just to note, no need to change the ids just because you changed the element type in HTML. In some sense it'd be better to leave the ids the same since the code here doesn't need to care about the change in the HTML.

2023-03-21 01:07 UTC, gigamonkey approved these changes
Looking good. You can merge this but keep the branch around.

2023-03-21 21:45 UTC, merged